# SPDX-FileCopyrightText: © 2025 Jinwoo Park (pmnxis@gmail.com)
#
# SPDX-License-Identifier: CC0-1.0

# See details : https://github.com/crate-ci/typos
[default.extend-words]
egui = "egui"
chama = "chama"
haachama = "haachama"
