# SPDX-FileCopyrightText: © 2020 emilk (emil.ernerfeldt@gmail.com)
#
# SPDX-License-Identifier: MIT OR Apache-2.0

on: [push, pull_request, workflow_dispatch]

name: CI

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  release_job:
    name: Create release
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Install libheif dependencies (macOS)
      run: |
        brew update
        brew install libheif pkg-config
    - name: Install kokai
      run: cargo install kokai
    - name: Make changelog
      run: kokai release --ref ${{ github.ref }} > changes
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        body_path: ./changes

  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libheif dependencies (macOS)
        run: |
          brew update
          brew install libheif pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Check spelling of entire workspace
        uses: crate-ci/typos@master

  test:
    name: Test Suite
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libheif dependencies (macOS)
        run: |
          brew update
          brew install libheif pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib

  fmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install libheif dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:strukturag/libheif
          sudo apt-get install -y libheif-dev libde265-dev libx265-dev libjpeg-dev libpng-dev libaom-dev libssl-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libheif dependencies (macOS)
        run: |
          brew update
          brew install libheif pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build_job:
    name: Build release
    # commend `needs: release_job` when you test ci/cd
    needs: release_job
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          TARGET: aarch64-apple-darwin

        # - os: macos-latest
        #   TARGET: x86_64-apple-darwin

        # - os: ubuntu-24.04
        #   TARGET: x86_64-unknown-linux-gnu

        - os: windows-2022
          TARGET: x86_64-pc-windows-msvc
          EXTENSION: .exe

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"

    # macOS
    - name: Install cargo bundle
      run: cargo install cargo-bundle
      if: matrix.os == 'macos-latest'

    - name: Install cargo universal2
      run: cargo install universal2
      if: matrix.os == 'macos-latest'

    - name: Install libheif dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install libheif x265 libde265 pkg-config

    # windows
    - name: Install libheif dependencies (Windows)
      if: matrix.os == 'windows-2022'
      shell: pwsh
      run: |
        vcpkg integrate install
        vcpkg install libheif:x64-windows-static-md
        vcpkg install libheif:x64-windows-static

    # common
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --release --target=${{ matrix.TARGET }}

    # macOS
    - name: Install cargo bundle
      if: matrix.os == 'macos-latest'
      run: ./build_mac.sh

    - name: Sign macOS App
      if: matrix.os == 'macos-latest'
      env:
        CERT_KEY_B64: ${{ secrets.CERT_KEY_B64 }}
        CERT_CRT_B64: ${{ secrets.CERT_CRT_B64 }}
        P12_PASS: ${{ secrets.P12_PASS }}
      run: bash ./codesign_mac.sh

    - name: Zip Mac Silicon Bundle
      if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'macos-latest'
      run: mv target/release/bundle/osx/Chama\ Optics.app . && zip -r chama_optics_macos_apple_silicon.zip Chama\ Optics.app

    # From here only works when there's tag starting with `v`
    - name: Upload Mac Release
      if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'macos-latest'
      id: upload-release-asset-mac
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release_job.outputs.upload_url }}
        asset_path: ChamaOptics-arm64.dmg
        asset_name: ChamaOptics-arm64.dmg
        asset_content_type: application/zip

    # windows
    - name: Upload Windows 2019 Release exe
      if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'windows-2022'
      id: upload-release-asset-windows-classic
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release_job.outputs.upload_url }}
        asset_path: target/x86_64-pc-windows-msvc/release/chama-optics.exe
        asset_name: chama-optics.exe
        asset_content_type: application/zip

  publish_release:
    name: Publish release
    needs: [build_job, release_job]
    runs-on: ubuntu-24.04
    steps:
    - name: Test id
      run: echo "${{ needs.release_job.outputs.release_id }}"
    - name: Test id 2
      run: echo "${{ needs.release_job.outputs.upload_url }}"
    - name: Publish
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release_job.outputs.release_id }}
